@startuml
'https://plantuml.com/sequence-diagram

class App{
    main()
    start()
}
class AppController{
    addList()
    removeList()
    saveList()
    saveAll()
    loadList()
}
class ToDo{
    +String dueDate
    +String description
    +char status
    +setDueDate
    +setDescription
    +setStatus
    +getDueDate
    +getDescription
    +getStatus
}

class csvHandler {
    + readCSV(filename)
    + writeCSV(List)
    + createFile(filename)
}
App -- AppController
AppController -- csvHandler
csvHandler - ToDo
@enduml